### ISSUE TITLE
Initialise method is not marked as throw, and no error models exist

### ISSUE THREAD

**Issue by jasonconnery** [tryterra/TerraiOS#1]
Hi there. the docs at https://docs.tryterra.co/reference/terra-ios-package say the following about initialisation:

> Please note this initialisation can fail by throwing the following errors: TerraError.HealthKitUnavailable, TerraError.UnexpectedError. Catch them and handle appropriately instead of forcing try!

However neither of these error models appear to exist currently.

Also `terra.initConnection` is not labelled as throwing, and results in a warning: `No calls to throwing functions occur within 'try' expression`

Attempting to call initConnection results in a fatalError , that cannot be caught and handled.

**Comment by jasonconnery** [comment]
More information on the fatal error when calling `initConnection`:

```
TerraiOS/Connections.swift:24: Fatal error
```

**Comment by elliottyu19** [comment]
Ahh sorry for the out of date docs! The docs should be all up to date now
